# Generated by Django 4.1 on 2022-11-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0010_review_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='favorites',
        ),
    ]
