# Generated by Django 4.1.2 on 2022-11-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0011_remove_review_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='favorites',
        ),
    ]
